// src/lib/country-names.ts
// Traducción de nombres de países EN → ES para la UI

const COUNTRY_ES: Record<string, string> = {
  'Afghanistan': 'Afganistán',
  'Albania': 'Albania',
  'Algeria': 'Argelia',
  'Andorra': 'Andorra',
  'Angola': 'Angola',
  'Argentina': 'Argentina',
  'Armenia': 'Armenia',
  'Australia': 'Australia',
  'Austria': 'Austria',
  'Azerbaijan': 'Azerbaiyán',
  'Bahrain': 'Baréin',
  'Bangladesh': 'Bangladés',
  'Barbados': 'Barbados',
  'Belarus': 'Bielorrusia',
  'Belgium': 'Bélgica',
  'Bermuda': 'Bermudas',
  'Bolivia': 'Bolivia',
  'Bosnia': 'Bosnia',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Botswana': 'Botsuana',
  'Brazil': 'Brasil',
  'Bulgaria': 'Bulgaria',
  'Burkina Faso': 'Burkina Faso',
  'Burundi': 'Burundi',
  'Cambodia': 'Camboya',
  'Cameroon': 'Camerún',
  'Canada': 'Canadá',
  'Chile': 'Chile',
  'China': 'China',
  'Colombia': 'Colombia',
  'Congo': 'Congo',
  'Congo DR': 'RD Congo',
  'Costa Rica': 'Costa Rica',
  'Croatia': 'Croacia',
  'Cuba': 'Cuba',
  'Cyprus': 'Chipre',
  'Czech Republic': 'República Checa',
  'Czech-Republic': 'República Checa',
  'Denmark': 'Dinamarca',
  'Dominican Republic': 'República Dominicana',
  'Ecuador': 'Ecuador',
  'Egypt': 'Egipto',
  'El Salvador': 'El Salvador',
  'England': 'Inglaterra',
  'Estonia': 'Estonia',
  'Ethiopia': 'Etiopía',
  'Faroe Islands': 'Islas Feroe',
  'Finland': 'Finlandia',
  'France': 'Francia',
  'Georgia': 'Georgia',
  'Germany': 'Alemania',
  'Ghana': 'Ghana',
  'Gibraltar': 'Gibraltar',
  'Greece': 'Grecia',
  'Guatemala': 'Guatemala',
  'Guyana': 'Guyana',
  'Haiti': 'Haití',
  'Honduras': 'Honduras',
  'Hong Kong': 'Hong Kong',
  'Hungary': 'Hungría',
  'Iceland': 'Islandia',
  'India': 'India',
  'Indonesia': 'Indonesia',
  'Iran': 'Irán',
  'Iraq': 'Irak',
  'Ireland': 'Irlanda',
  'Republic of Ireland': 'Irlanda',
  'Israel': 'Israel',
  'Italy': 'Italia',
  'Ivory Coast': 'Costa de Marfil',
  'Ivory-Coast': 'Costa de Marfil',
  'Jamaica': 'Jamaica',
  'Japan': 'Japón',
  'Jordan': 'Jordania',
  'Kazakhstan': 'Kazajistán',
  'Kenya': 'Kenia',
  'Kosovo': 'Kosovo',
  'Kuwait': 'Kuwait',
  'Kyrgyzstan': 'Kirguistán',
  'Laos': 'Laos',
  'Latvia': 'Letonia',
  'Lebanon': 'Líbano',
  'Libya': 'Libia',
  'Liechtenstein': 'Liechtenstein',
  'Lithuania': 'Lituania',
  'Luxembourg': 'Luxemburgo',
  'Malaysia': 'Malasia',
  'Maldives': 'Maldivas',
  'Malta': 'Malta',
  'Mexico': 'México',
  'Moldova': 'Moldavia',
  'Mongolia': 'Mongolia',
  'Montenegro': 'Montenegro',
  'Morocco': 'Marruecos',
  'Mozambique': 'Mozambique',
  'Myanmar': 'Myanmar',
  'Namibia': 'Namibia',
  'Nepal': 'Nepal',
  'Netherlands': 'Países Bajos',
  'New Zealand': 'Nueva Zelanda',
  'New-Zealand': 'Nueva Zelanda',
  'Nicaragua': 'Nicaragua',
  'Nigeria': 'Nigeria',
  'North Macedonia': 'Macedonia del Norte',
  'North-Macedonia': 'Macedonia del Norte',
  'Northern Ireland': 'Irlanda del Norte',
  'Northern-Ireland': 'Irlanda del Norte',
  'Norway': 'Noruega',
  'Oman': 'Omán',
  'Pakistan': 'Pakistán',
  'Palestine': 'Palestina',
  'Panama': 'Panamá',
  'Paraguay': 'Paraguay',
  'Peru': 'Perú',
  'Philippines': 'Filipinas',
  'Poland': 'Polonia',
  'Portugal': 'Portugal',
  'Puerto Rico': 'Puerto Rico',
  'Qatar': 'Catar',
  'Romania': 'Rumania',
  'Russia': 'Rusia',
  'Rwanda': 'Ruanda',
  'San Marino': 'San Marino',
  'Saudi Arabia': 'Arabia Saudita',
  'Saudi-Arabia': 'Arabia Saudita',
  'Scotland': 'Escocia',
  'Senegal': 'Senegal',
  'Serbia': 'Serbia',
  'Singapore': 'Singapur',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'South Africa': 'Sudáfrica',
  'South-Africa': 'Sudáfrica',
  'South Korea': 'Corea del Sur',
  'South-Korea': 'Corea del Sur',
  'Spain': 'España',
  'Sri Lanka': 'Sri Lanka',
  'Sudan': 'Sudán',
  'Suriname': 'Surinam',
  'Sweden': 'Suecia',
  'Switzerland': 'Suiza',
  'Syria': 'Siria',
  'Tajikistan': 'Tayikistán',
  'Tanzania': 'Tanzania',
  'Thailand': 'Tailandia',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Trinidad-And-Tobago': 'Trinidad y Tobago',
  'Tunisia': 'Túnez',
  'Turkey': 'Turquía',
  'Turkmenistan': 'Turkmenistán',
  'UAE': 'Emiratos Árabes',
  'USA': 'Estados Unidos',
  'Uganda': 'Uganda',
  'Ukraine': 'Ucrania',
  'Uruguay': 'Uruguay',
  'Uzbekistan': 'Uzbekistán',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietnam',
  'Wales': 'Gales',
  'World': 'Internacional',
  'Yemen': 'Yemen',
  'Zambia': 'Zambia',
  'Zimbabwe': 'Zimbabue',
};

/**
 * Traduce el nombre de un país del inglés al español.
 * Si no hay traducción, devuelve el nombre original.
 */
export function translateCountry(country: string): string {
  return COUNTRY_ES[country] || country;
}
