import { CSSProperties } from 'react';

export const C = {
  bgDeep:'#050810', bgPrimary:'#0a0e17', bgSurface:'#0f1420', bgElevated:'#151b2b',
  bgCard:'#121828', bgHover:'#1a2235', bgInput:'#0d1219',
  borderSubtle:'rgba(255,255,255,0.06)', borderDefault:'rgba(255,255,255,0.08)', borderStrong:'rgba(255,255,255,0.12)',
  emerald:'#10b981', emeraldDim:'#0d9668', emeraldGlow:'rgba(16,185,129,0.15)',
  cyan:'#06b6d4', cyanDim:'#0891b2', cyanGlow:'rgba(6,182,212,0.12)',
  amber:'#f59e0b', amberDim:'#d97706', amberGlow:'rgba(245,158,11,0.12)',
  red:'#ef4444', redGlow:'rgba(239,68,68,0.15)',
  textPrimary:'#f1f5f9', textSecondary:'#94a3b8', textMuted:'#64748b', textFaint:'#475569',
} as const;

export const fonts = {
  display:"'Space Grotesk', system-ui, -apple-system, sans-serif",
  mono:"'JetBrains Mono', 'SF Mono', monospace",
  body:"'Space Grotesk', system-ui, -apple-system, sans-serif",
} as const;

export const S = {
  pageContainer: { maxWidth:960, margin:'0 auto', padding:'0 16px' } as CSSProperties,
  pageContainerWide: { maxWidth:1200, margin:'0 auto', padding:'0 16px' } as CSSProperties,
  navbar: { position:'sticky' as const, top:0, zIndex:50, background:'rgba(5,8,16,0.85)', backdropFilter:'blur(20px) saturate(180%)', WebkitBackdropFilter:'blur(20px) saturate(180%)', borderBottom:`1px solid ${C.borderSubtle}`, padding:'12px 24px', display:'flex', alignItems:'center', justifyContent:'space-between', gap:16 } as CSSProperties,
  navBrand: { fontFamily:fonts.display, fontSize:'1.25rem', fontWeight:700, color:C.textPrimary, textDecoration:'none', display:'flex', alignItems:'center', gap:8, letterSpacing:'-0.02em' } as CSSProperties,
  navBrandGradient: { background:`linear-gradient(135deg, ${C.emerald}, ${C.cyan})`, WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' } as CSSProperties,
  navLink: { fontSize:'0.8125rem', fontWeight:500, color:C.textSecondary, textDecoration:'none', padding:'8px 12px', borderRadius:10, transition:'all 150ms ease', display:'flex', alignItems:'center', gap:6, whiteSpace:'nowrap' as const } as CSSProperties,
  navLinkActive: { color:C.emerald, background:C.emeraldGlow } as CSSProperties,
  hero: { position:'relative' as const, padding:'64px 24px', textAlign:'center' as const, overflow:'hidden' } as CSSProperties,
  heroTitle: { fontFamily:fonts.display, fontSize:'clamp(2.25rem, 5vw, 3.5rem)', fontWeight:700, letterSpacing:'-0.03em', lineHeight:1.1, marginBottom:16, color:C.textPrimary } as CSSProperties,
  heroSubtitle: { fontSize:'clamp(0.9375rem, 2vw, 1.125rem)', color:C.textSecondary, maxWidth:540, margin:'0 auto 32px', lineHeight:1.7 } as CSSProperties,
  heroActions: { display:'flex', gap:12, justifyContent:'center', flexWrap:'wrap' as const } as CSSProperties,
  gradientText: { background:`linear-gradient(135deg, ${C.emerald}, ${C.cyan})`, WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' } as CSSProperties,
  btn: { display:'inline-flex', alignItems:'center', gap:8, fontFamily:fonts.body, fontSize:'0.875rem', fontWeight:600, padding:'10px 20px', borderRadius:10, border:'none', cursor:'pointer', transition:'all 150ms ease', textDecoration:'none', whiteSpace:'nowrap' as const } as CSSProperties,
  btnPrimary: { background:C.emerald, color:'#fff', boxShadow:'0 2px 12px rgba(16,185,129,0.25)' } as CSSProperties,
  btnSecondary: { background:C.bgElevated, color:C.textPrimary, border:`1px solid ${C.borderDefault}` } as CSSProperties,
  btnGhost: { background:'transparent', color:C.textSecondary, border:`1px solid ${C.borderSubtle}` } as CSSProperties,
  statsGrid: { display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:16, maxWidth:700, margin:'48px auto 0' } as CSSProperties,
  statCard: { background:C.bgCard, border:`1px solid ${C.borderSubtle}`, borderRadius:14, padding:'24px 16px', textAlign:'center' as const } as CSSProperties,
  statValue: { fontFamily:fonts.mono, fontSize:'1.75rem', fontWeight:700, lineHeight:1, marginBottom:4 } as CSSProperties,
  statLabel: { fontSize:'0.6875rem', color:C.textMuted, textTransform:'uppercase' as const, letterSpacing:'0.08em', fontWeight:500 } as CSSProperties,
  sectionHeader: { display:'flex', alignItems:'center', justifyContent:'space-between', padding:'16px 24px' } as CSSProperties,
  sectionTitle: { fontFamily:fonts.display, fontSize:'1.125rem', fontWeight:600, display:'flex', alignItems:'center', gap:8, color:C.textPrimary } as CSSProperties,
  sectionBadge: { fontFamily:fonts.mono, fontSize:'0.6875rem', fontWeight:600, background:C.emeraldGlow, color:C.emerald, padding:'2px 8px', borderRadius:9999 } as CSSProperties,
  sectionLink: { fontSize:'0.8125rem', color:C.textMuted, textDecoration:'none' } as CSSProperties,
  matchCard: { display:'grid', gridTemplateColumns:'1fr auto 1fr', alignItems:'center', gap:12, padding:'16px 24px', background:C.bgSurface, border:`1px solid ${C.borderSubtle}`, borderRadius:14, transition:'all 150ms ease', textDecoration:'none', color:'inherit', cursor:'pointer' } as CSSProperties,
  matchCardLive: { borderLeft:`3px solid ${C.emerald}`, background:`linear-gradient(90deg, ${C.emeraldGlow}, ${C.bgSurface} 30%)` } as CSSProperties,
  matchRow: { display:'grid', gridTemplateColumns:'1fr auto 1fr', alignItems:'center', gap:12, padding:'12px 24px', background:C.bgSurface, transition:'background 150ms ease', textDecoration:'none', color:'inherit', cursor:'pointer' } as CSSProperties,
  matchRowLive: { background:`linear-gradient(90deg, ${C.emeraldGlow}, ${C.bgSurface} 20%)` } as CSSProperties,
  team: { display:'flex', alignItems:'center', gap:8, minWidth:0 } as CSSProperties,
  teamAway: { justifyContent:'flex-end', textAlign:'right' as const } as CSSProperties,
  teamLogo: { width:28, height:28, borderRadius:6, objectFit:'contain' as const, flexShrink:0 } as CSSProperties,
  teamName: { fontSize:'0.875rem', fontWeight:500, color:C.textPrimary, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' as const } as CSSProperties,
  leagueHeader: { display:'flex', alignItems:'center', gap:8, padding:'12px 24px', fontSize:'0.75rem', color:C.textMuted, fontWeight:500, textTransform:'uppercase' as const, letterSpacing:'0.06em', borderBottom:`1px solid ${C.borderSubtle}`, position:'sticky' as const, top:56, background:C.bgDeep, zIndex:10 } as CSSProperties,
  leagueFlag: { width:16, height:16, borderRadius:2 } as CSSProperties,
  exploreGrid: { display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(200px, 1fr))', gap:16, padding:'0 24px' } as CSSProperties,
  exploreCard: { background:C.bgCard, border:`1px solid ${C.borderSubtle}`, borderRadius:14, padding:'32px 24px', textDecoration:'none', color:'inherit', transition:'all 250ms ease', display:'flex', flexDirection:'column' as const, gap:8 } as CSSProperties,
  badgeLive: { fontFamily:fonts.mono, fontSize:'0.6875rem', fontWeight:600, padding:'2px 8px', borderRadius:9999, textTransform:'uppercase' as const, letterSpacing:'0.04em', background:C.emeraldGlow, color:C.emerald, border:'1px solid rgba(16,185,129,0.3)' } as CSSProperties,
  badgeFinished: { fontFamily:fonts.mono, fontSize:'0.6875rem', fontWeight:600, padding:'2px 8px', borderRadius:9999, background:C.bgElevated, color:C.textMuted } as CSSProperties,
  badgeScheduled: { fontFamily:fonts.mono, fontSize:'0.6875rem', fontWeight:600, padding:'2px 8px', borderRadius:9999, background:C.cyanGlow, color:C.cyan, border:'1px solid rgba(6,182,212,0.3)' } as CSSProperties,
  dateBtn: { fontFamily:fonts.body, fontSize:'0.8125rem', fontWeight:500, padding:'8px 16px', borderRadius:9999, border:`1px solid ${C.borderSubtle}`, background:'transparent', color:C.textSecondary, cursor:'pointer', whiteSpace:'nowrap' as const, transition:'all 150ms ease', textDecoration:'none' } as CSSProperties,
  dateBtnActive: { background:C.emerald, color:'#fff', borderColor:C.emerald } as CSSProperties,
  filterChip: { display:'inline-flex', alignItems:'center', gap:6, fontSize:'0.75rem', fontWeight:500, padding:'5px 12px', borderRadius:9999, background:C.bgElevated, color:C.textSecondary, border:`1px solid ${C.borderSubtle}`, cursor:'pointer', whiteSpace:'nowrap' as const } as CSSProperties,
  filterChipActive: { background:C.emeraldGlow, borderColor:'rgba(16,185,129,0.3)', color:C.emerald } as CSSProperties,
  chatContainer: { display:'flex', flexDirection:'column' as const, height:'calc(100dvh - 56px)', maxWidth:720, margin:'0 auto', position:'relative' as const } as CSSProperties,
  chatMessages: { flex:1, overflowY:'auto' as const, padding:24, display:'flex', flexDirection:'column' as const, gap:16 } as CSSProperties,
  chatBubbleBot: { maxWidth:'85%', padding:'16px 24px', borderRadius:'14px 14px 14px 6px', fontSize:'0.9375rem', lineHeight:1.65, background:C.bgCard, border:`1px solid ${C.borderSubtle}`, alignSelf:'flex-start' } as CSSProperties,
  chatBubbleUser: { maxWidth:'85%', padding:'16px 24px', borderRadius:'14px 14px 6px 14px', fontSize:'0.9375rem', lineHeight:1.65, background:`linear-gradient(135deg, ${C.emerald}, ${C.cyan})`, color:'#fff', alignSelf:'flex-end' } as CSSProperties,
  chatInputBar: { display:'flex', gap:8, padding:'16px 24px', borderTop:`1px solid ${C.borderSubtle}`, background:C.bgPrimary } as CSSProperties,
  chatInput: { flex:1, background:C.bgInput, border:`1px solid ${C.borderDefault}`, borderRadius:10, padding:'12px 16px', color:C.textPrimary, fontFamily:fonts.body, fontSize:'0.875rem', outline:'none' } as CSSProperties,
  disclaimer: { display:'flex', alignItems:'center', gap:8, fontSize:'0.75rem', color:C.textMuted, padding:'16px 24px' } as CSSProperties,
  glass: { background:'rgba(15,20,32,0.7)', backdropFilter:'blur(16px) saturate(180%)', WebkitBackdropFilter:'blur(16px) saturate(180%)', border:`1px solid ${C.borderSubtle}` } as CSSProperties,
} as const;

export default S;